name: build

on:
  push:
      branches:
        - 'master'
  pull_request: ~

jobs:
    test:
        name: "Functional Test"

        strategy:
            fail-fast: false
            matrix:
                php-versions: [ '7.3', '7.4' ]
                flow-versions: [ '6.3', '7.0' ]
                include:
                    - php-versions: '7.2'
                      flow-versions: '6.0'

        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    path: ${{ env.FLOW_FOLDER }}

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    extensions: mbstring, xml, json, zlib, iconv, intl, pdo_sqlite
                    ini-values: date.timezone="Africa/Tunis", opcache.fast_shutdown=0, apc.enable_cli=on

            -   name: Set Flow Version
                run: composer require neos/flow ^${{ matrix.flow-versions }} --no-progress --no-interaction

            -   name: Run Functional Tests
                run: composer test:functional

            -   name: Run Static Analysis
                run: composer test:stan
